
export const SIGNUP_USER = "SIGNUP_USER"
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

export const SIGNIN_USER = "SIGNIN_USER"
export const LOGGIN_USER = "LOGGIN_USER"